#!/bin/bash

using_pylib=""

data_info="./$SK_PRJ_NAME/.dbg/prj.info"
linked_lib=$(cat $data_info | grep "lib:" | cut -d':' -f2-)
linked_folders=$(cat $data_info | grep "folders:" | cut -d':' -f2-)

include_linked_folders=""
addsubdir_linked_folders=""
eval "linked_folders_arr=($linked_folders)"
for folder in "${linked_folders_arr[@]}";do
	safe_name=$(echo "$folder" | tr '/' '_')
	include_linked_folders+="-include $safe_name/subdir.mk"$'\n'
	addsubdir_linked_folders+="$safe_name \\"$'\n'
done



echo "ASM_SRCS := 
C++M_SRCS := 
C++_SRCS := 
CCM_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXXM_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
O_SRCS := 
SX_SRCS := 
S_UPPER_SRCS := 
C++M_DEPS := 
C++_DEPS := 
CCM_DEPS := 
CC_DEPS := 
CPP_DEPS := 
CXXM_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 

SUBDIRS := \\
. \\
$addsubdir_linked_folders
" > $SK_PRJ_NAME/.dbg/sources.mk
export using_pylib=""
bash "$SK_PRJ_MANAGER/res/generate_subdir_file"\
 "$SK_PRJ_NAME/*.*"\
 ".."\
 "./bin"\
 "$SK_PRJ_NAME/.dbg/subdir.mk"\
 ""\

echo "-include ../makefile.init 
RM := rm -rf

-include sources.mk

$include_linked_folders
-include subdir.mk
ifneq (\$(MAKECMDGOALS),clean)
ifneq (\$(strip \$(C++M_DEPS)),)
-include \$(C++M_DEPS)
endif
ifneq (\$(strip \$(C++_DEPS)),)
-include \$(C++_DEPS)
endif
ifneq (\$(strip \$(CCM_DEPS)),)
-include \$(CCM_DEPS)
endif
ifneq (\$(strip \$(CC_DEPS)),)
-include \$(CC_DEPS)
endif
ifneq (\$(strip \$(CPP_DEPS)),)
-include \$(CPP_DEPS)
endif
ifneq (\$(strip \$(CXXM_DEPS)),)
-include \$(CXXM_DEPS)
endif
ifneq (\$(strip \$(CXX_DEPS)),)
-include \$(CXX_DEPS)
endif
ifneq (\$(strip \$(C_DEPS)),)
-include \$(C_DEPS)
endif
ifneq (\$(strip \$(C_UPPER_DEPS)),)
-include \$(C_UPPER_DEPS)
endif
endif

-include ../makefile.defs

OPTIONAL_TOOL_DEPS := \\
\$(wildcard ../makefile.defs) \\
\$(wildcard ../makefile.init) \\
\$(wildcard ../makefile.targets) \\

BUILD_ARTIFACT_NAME := app
BUILD_ARTIFACT_EXTENSION :=
BUILD_ARTIFACT_PREFIX :=
BUILD_ARTIFACT := \$(BUILD_ARTIFACT_PREFIX)\$(BUILD_ARTIFACT_NAME)\$(if \$(BUILD_ARTIFACT_EXTENSION),.\$(BUILD_ARTIFACT_EXTENSION),)

all: main-build
main-build: app

app: \$(OBJS) \$(USER_OBJS) makefile \$(OPTIONAL_TOOL_DEPS)
	@echo 'Building target: \$@'
	@echo 'Invoking: GCC C++ Linker',
	@echo 'Finished building target: \$@'
	$(<$SK_PRJ_MANAGER/res/templates/prj-type/$SK_PRJ_TYPE/cmpl_cmnd) $using_pylib $linked_lib
	@echo 'Finished building target: \$@'
	@echo ' '

dbg: main-dbg
main-dbg: dbg_app

dbg_app: \$(OBJS) \$(USER_OBJS) makefile \$(OPTIONAL_TOOL_DEPS)
	@echo 'Building target: \$@'
	@echo 'Invoking: GCC C++ Linker',
	@echo 'Finished building target: \$@'
	$(<$SK_PRJ_MANAGER/res/templates/prj-type/$SK_PRJ_TYPE/cmpl_cmnd) -g $using_pylib $linked_lib
	@echo 'Finished building target: \$@'
	@echo ' '

clean:
	-\$(RM) result/app
	-@echo ' '
.PHONY: all clean dependents main-build

-include ../makefile.targets" > $SK_PRJ_NAME/.dbg/makefile
