#!/bin/bash
files=($1)

if [[ -z $5 || $5 == "" ]];then
	clear_name="-2e-"
else
	clear_name="$3"
fi

data_info="./$SK_PRJ_NAME/.dbg/prj.info"
linked_includes=$(cat $data_info | grep "includes:" | cut -d':' -f2-)

echo "C++_SRCS += \\
$(for file in "${files[@]}"; do
	base=$(basename "$file" .*)
	if [[ ${base##*.} != "h" || ${base##*.} != "h++" || ${base##*.} != "hpp" ]];then
		echo "$2/$base \\"
		if [[ ${base##*.} == "pyx" && ! -z $using_pylib ]];then
			using_pylib=" -l\"python3.13\""
			export using_pylib
		fi
	fi
done)


C++_DEPS += \\
$(for file in "${files[@]}"; do
	base=$(basename "$file" .*)
	if [[ ${base##*.} != "h" || ${base##*.} != "h++" || ${base##*.} != "hpp" ]];then
		if [[ ${base##*.} == "c" || ${base##*.} == "C" ]];then
			echo "$3/${base%.*}.d \\"
		else
			echo "$3/$base.d \\"
		fi
	fi
done)


OBJS += \\
$(for file in "${files[@]}"; do
	base=$(basename "$file" .*)
	if [[ ${base##*.} != "h" || ${base##*.} != "h++" || ${base##*.} != "hpp" ]];then
		if [[ ${base##*.} == "c" || ${base##*.} == "C" ]];then
			echo "$3/${base%.*}.o \\"
		else
			echo "$3/$base.o \\"
		fi
	fi
done)



$3/%.pyx.o: $2/%.pyx subdir.mk
	@echo 'Building file: \$<'
	@echo 'Invoking: Cython Compiler'
	cython -o \"$3/nonezst/\$<.c\" \"\$<\" --3str
	gcc $linked_includes -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF\"./\$(@:%.o=%.d)\" -MT\"\$@\" -o \"\$@\" \"$3/nonezst/\$<.c\" $(python3-config --ldflags)
	@echo 'Finished building: \$<'
	@echo ' '
$3/%.pyxx.o: $2/%.pyxx subdir.mk
	@echo 'Building file: \$<'
	@echo 'Invoking: Cython Compiler'
	cython --cplus -o \"$3/nonezst/\$<.c++\" \"\$<\" --3str
	g++ -fmodules $linked_includes -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF\"./\$(@:%.o=%.d)\" -MT\"\$@\" -o \"\$@\" \"$3/nonezst/\$<.c++\" $(python3-config --ldflags)
	@echo 'Finished building: \$<'
	@echo ' '


$3/%.s.o: $2/%.s subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: (GNU as) Assembly Compiler'
	as -g -o \"\$@\" \"\$<\"
	@echo 'Finished building: \$<'
	@echo ' '

$3/%.asm.o: $2/%.asm subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: (GNU as) Assembly Compiler'
	as -g -o \"\$@\" \"\$<\"
	@echo 'Finished building: \$<'
	@echo ' '



$3/%.go.o: $2/%.go subdir.mk
	@echo 'Building file: \$<'
	@echo 'Invoking: GO Compiler'
	go tool compile -o \"\$@\" \"\$<\"
	@echo 'Finished building: \$<'
	@echo ' '



$3/%.class: $2/%.java subdir.mk
	@echo 'Building file: \$<'
	@echo 'Invoking: Javac java Compiler'
	javac -d \"./\" \"\$<\"
	@echo 'Finished building: \$<'
	@echo ' '



$3/%.cpp.o: $2/%.cpp subdir.mk
	@echo 'Building file: \$<'
	@echo 'Invoking: G++ C++ Compiler'
	g++ -std=c++2c $linked_includes -fmodules -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF\"./\$(@:%.o=%.d)\" -MT\"\$@\" -o \"\$@\" \"\$<\"
	@echo 'Finished building: \$<'
	@echo ' '
$3/%.c++.o: $2/%.c++ subdir.mk
	@echo 'Building file: \$<'
	@echo 'Invoking: G++ C++ Compiler'
	g++ -std=c++2c $linked_includes -fmodules -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF\"./\$(@:%.o=%.d)\" -MT\"\$@\" -o \"\$@\" \"\$<\"
	@echo 'Finished building: \$<'
	@echo ' '
$3/%.cc.o: $2/%.cc subdir.mk
	@echo 'Building file: \$<'
	@echo 'Invoking: G++ C++M Compiler'
	g++ -std=c++2c $linked_includes -fmodules -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF\"./\$(@:%.o=%.d)\" -MT\"\$@\" -o \"\$@\" \"\$<\"
	@echo 'Finished building: \$<'
	@echo ' '
$3/%.cppm.o: $2/%.cppm subdir.mk
	@echo 'Building file: \$<'
	@echo 'Invoking: G++ C++M Compiler'
	g++ -std=c++2c $linked_includes -fmodules -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF\"./\$(@:%.o=%.d)\" -MT\"\$@\" -o \"\$@\" \"\$<\"
	@echo 'Finished building: \$<'
	@echo ' '
$3/%.c++m.o: $2/%.c++m subdir.mk
	@echo 'Building file: \$<'
	@echo 'Invoking: G++ C++M Compiler'
	g++ -std=c++2c $linked_includes -fmodules -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF\"./\$(@:%.o=%.d)\" -MT\"\$@\" -o \"\$@\" \"\$<\"
	@echo 'Finished building: \$<'
	@echo ' '

$3/%.o: $2/%.c subdir.mk
	@echo 'Building file: \$<'
	@echo 'Invoking: GCC C Compiler'
	gcc $linked_includes -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF\"./\$(@:%.o=%.d)\" -MT\"\$@\" -o \"\$@\" \"\$<\"
	@echo 'Finished building: \$<'
	@echo ' '


clean: clean-$clear_name

clean-$clear_name:
	-\$(RM) $3/*

.PHONY: clean-$clear_name" > $4
