#!/bin/bash

if [[ $1 == "--help" ]];then
	printf "\e[1;30mhave to run this script with \e[1;33msource\e[1;30m to export the Variables\e[0m\n"
	printf "\e[7mUse For:\e[0m\n\tset the project type\n"
	printf "\e[7mThe How to Using:\e[0m\n\tskprj <type> [arguments]\n"
	printf "\t\t      [\e[1;32m-n\e[0m:SK_PRJ_TYPE\e[1;30m= exported-form:<new> by default\e[0m]\n"
	printf "\e[7mArgs:\e[0m\n"
	printf "\t1)\e[1;32mSK_PRJ_TYPE\e[0m: the project type \e[1;30m:project templates in 'skprjm/res/templates/prj-type'\e[0m\n"
	printf "\nThis Args can select by tags: \e[1;32m-s:for set\e[0m\n"
	return 5
fi

if [[ $1 == "-s" ]];then
	is_set='y'
	shift
fi

if [[ -z $SK_PRJ_TYPE && -z $1 ]];then
	printf "\e[1;32mproject type\e[0m:"
	read SK_PRJ_TYPE
	export SK_PRJ_TYPE
fi

if [[ ! -z $is_set ]];then
	if [[ -z $1 ]]; then
		printf "\e[1;32mproject type\e[0m:"
		read SK_PRJ_TYPE
		export SK_PRJ_TYPE
	fi
	SK_PRJ_TYPE=$1
	export SK_PRJ_TYPE
else
	echo $SK_PRJ_TYPE
fi

if [[ ! -d "$SK_PRJ_MANAGER/res/templates/prj-type/$SK_PRJ_TYPE" ]];then
	printf "\e[1;31mThere is not such Type or Template call '$SK_PRJ_TYPE'\e[0m\n\tyou have to select one of those:\n"
	bash "$SK_PRJ_MANAGER/res/print_prj-type_info"
	printf "\e[1;31mIf you change the name but it steel the old one make sure to run this script with '\e[1;33msource\e[1;31m'\e[0m\n"
fi
