#!/bin/bash
printf "give a formate for the 'main' file [Py/pYx/pyxx]: "
read format
format=${format,,}
if [[ $format != "py" && $format != "pyx" && $format != "pyxx" ]];then
	printf "\e[1;33mWarning\e[0m: format.$format is not a python file format\n\tIt will changed auto to \e[1;35m'py'\e[0m\n"
fi

cp $SK_PRJ_MANAGER/res/templates/files/main.$format  $SK_PRJ_NAME
if [[ $format == "pyx" ]];then
	cp $SK_PRJ_MANAGER/res/templates/files/z_sk_cy_launcher.c++  $SK_PRJ_NAME
fi

if [[ $format == "py" ]];then
	echo "printf \"\e[1;33mWarning\e[0m: This project is not compiled\n\tYou can run it with: skprj <run> \$@\n\"" > $SK_PRJ_NAME/.dbg/build
	echo "printf \"\e[1;33mWarning\e[0m: This project is not compiled\n\tYou There is no output files to delete\n\"" > $SK_PRJ_NAME/.dbg/clear
	echo "python main.py \$@" > $SK_PRJ_NAME/.dbg/run
	rm -rf $SK_PRJ_NAME/.dbg/bin $SK_PRJ_NAME/.dbg/result $SK_PRJ_NAME/.dbg/prj.info
	touch $SK_PRJ_NAME/.dbg/prj.info
else
	py_path=$(python3-config --includes | cut -d' ' -f1-)
	bash $SK_PRJ_MANAGER/src/link -i $py_path
fi
