#!/bin/bash
printf "give a formate for the 'main' file: "
read format
format=${format,,}

if [[ $format == "cpp" ]];then
	format="c++"
fi

echo "format: $format"

if [[ -f $SK_PRJ_MANAGER/res/templates/files/main.$format ]];then
	cp -r $SK_PRJ_MANAGER/res/templates/files/main.$format $SK_PRJ_NAME/main.$format
else
	echo "this format.$format is not supported!"
	echo "it's will create a empty file"
	touch $SK_PRJ_NAME/main.$format
fi
