#!/bin/bash
if [[ $1 == "--help" ]];then
	printf "\e[7mUse For:\e[0m\n\trun terminal commands in project path\n"
	printf "\e[7mThe How to Using:\e[0m\n\tskprj <-:> [arguments]\n"
	printf "\t\t    [/bin/*] [/usr/bin/*] [/usr/local/bin/*] [...]\n"
	printf "\e[7mArgs:\e[0m\n"
	printf "\*)\e[1;32mCommand\e[0m: write any command \e[1;30m:well run in the project directory\e[0m\n"
	printf "This program just 'cd' into project path and run command in it\e[1;33m\n\tyou can face some problem with \e[1;35m'echo \"...\" > file'\e[1;30m :will apply it in workspace directory\e[0m\n"
	return 5
fi

action=$1
shift
source cd "$PWD/$SK_PRJ_NAME"
$action $@
