#!/bin/bash

if [[ $1 == "--help" ]];then
	printf "\e[7mUse For:\e[0m\n\tclean the project from Generated output files\n"
	printf "\e[7mThe How to Using:\e[0m\n\tskprj <clear> [arguments]\n"
	printf "\t\t      [\e[1;32m-n\e[0m:SK_PRJ_NAME\e[1;30m= exported-form:<new> by default\e[0m]\n"
	printf "\e[7mArgs:\e[0m\n"
	printf "\t1)\e[1;32mSK_PRJ_NAME\e[0m: the project name \e[1;30m:to control the project form workspace path\e[0m\n"
	printf "\nThis Args can select by tags: \e[1;32m-n:for name\e[0m\n"
	printf "if you using this with no argument and '\$SK_PRJ_NAME' are not define: \e[1;32mit will ask you for a prj-name\e[0m\n"
	return 5
fi

if [[ -z $1 ]]; then
	if [[ -z $SK_PRJ_NAME ]];then
		printf "project name:"
		read SK_PRJ_NAME
		if [[ -z SK_PRJ_NAME ]];then
			SK_PRJ_NAME="."
		fi
	fi
else
	if [[ -z $SK_PRJ_NAME ]];then
		SK_PRJ_NAME=$1
		shift
	fi
fi

cd $SK_PRJ_NAME/.dbg
if [[ -f "./.dbg/clear" ]];then
	bash ".dbg/clear"
else
	make clean
fi
