#!/bin/bash
if [[ $1 == "--help" ]];then
	printf "\e[7mUse For:\e[0m\n\tcopy the content of project to other directory\n"
	printf "\e[7mThe How to Using:\e[0m\n\tskprj <cp> [arguments]\n"
	printf "\t\t   [cp_to_path]\n"
	printf "\e[7mArgs:\e[0m\n"
	printf "\t1)\e[1;32mcp_to_path\e[0m: new project folder name \e[1;30m:create new directory and copy the project to it\e[0m\n"
	printf "\nIf you using this with '\$SK_PRJ_NAME' not define: \e[1;32mit will ask you for a prj-name\e[0m\n"
	return 5
fi

if [[ -z $SK_PRJ_NAME ]];then
	printf "project name:"
	read SK_PRJ_NAME
fi

if [[ -z $1 ]];then
	printf "copy to: "
	read cp_to_path
else
	cp_to_path=$1
fi

mkdir -p $cp_to_path
cp -r $SK_PRJ_NAME/* $cp_to_path
echo "project '$SK_PRJ_NAME' copy to '$cp_to_path'"
