#!/bin/bash
if [[ $1 == "--help" ]];then
	printf "\e[1;30mthis script can't apply for project that not generate an executable or not core.dump\e[0m\n"
	printf "\e[7mUse For:\e[0m\n\tCompile and run the project in \e[1;35mDebug-Mode\e[0m\n"
	printf "\e[7mThe How to Using:\e[0m\n\tskprj <dbg> [arguments]\n"
	printf "\t\t    [\e[1;32m-n\e[0m:SK_PRJ_NAME\e[1;30m= exported-form:<new> by default\e[0m]\n"
	printf "\e[7mArgs:\e[0m\n"
	printf "\t1)\e[1;32mSK_PRJ_NAME\e[0m: the project name \e[1;30m:to control the project form workspace path\e[0m\n"
	printf "\nIf you using this with no argument and '\$SK_PRJ_NAME' are not define: \e[1;32mit will ask you for a prj-name\e[0m\n"
	return 5
fi



if [[ -z $1 ]]; then
	if [[ -z $SK_PRJ_NAME ]];then
		printf "project name:"
		read SK_PRJ_NAME
		if [[ -z SK_PRJ_NAME ]];then
			SK_PRJ_NAME="."
		fi
	fi
else
	if [[ -z $SK_PRJ_NAME ]];then
		SK_PRJ_NAME=$1
		shift
	fi
fi



cd $SK_PRJ_NAME

if [[ -f ".dbg/dbg" ]];then
	bash ".dbg/dbg"
else
	bash "$SK_PRJ_MANAGER/res/default_dbg"
fi


printf "\e[1;33mThe program have compiled\e[0m  Do you want to continue [Y/n]? "
read a
if [[ $a == 'n' || $a == 'N' ]];then
	exit 0
fi



if [[ $(ulimit) != "unlimited" ]];then
	printf "\e[1;33mWarning\e[0m: the size of core file is limited ('$(ulimit)'), it's batter to make it 'unlimited'\n\tuse 'ulimit -c unlimited'"
fi



old_="$(cat /proc/sys/kernel/core_pattern)"
mkdir -p "./.dbg/tmp"



echo "./.dbg/tmp/app.core.%p" | sudo tee $pattern_path



if [[ -f ".dbg/run.dbg" ]];then
	bash ".dbg/run.dbg" $@
else
	./.dbg/result/app $@
fi



printf "\n\n\e[1;31mThe program crashed\e[0m  Do you want to continue to start debuging [Y/n]? "
read a
if [[ $a == 'y' || $a == 'Y' ]];then
	if [[ ! -f "./.dbg/result/app" ]];then
		printf "\e[1;31mError\e[0m: the file './.dbg/result/app' not found\n\tretry to build or debug the project\n"
	else
		list="$(ls ./.dbg/tmp/*)"
		echo "list:$list"
		if [[ -f "$list" ]];then
			gdb ./.dbg/result/app "$list"
			rm -rf ./.dbg/tmp/*
		else
			printf "\e[1;31mError\e[0m: There is no Generated '$list' file\n"
		fi
	fi
fi

echo "$old_" | sudo tee $pattern_path
