#!/bin/bash
if [[ $1 == "--help" ]];then
	printf "\e[7mUse For:\e[0m\n\tShow All the projects in this workspace\n"
	printf "\e[7mThe How to Using:\e[0m\n\tskprj <list> [arguments]\n"
	printf "\t\t     [\e[1;32m-n\e[0m:workspace_path\e[1;30m= \$PWD by default\e[0m]\n"
	printf "\e[7mArgs:\e[0m\n"
	printf "\t1)\e[1;32mworkspace_path\e[0m: the path to workspace that we want see \e[1;30m:to show the project form workspace path\e[0m\n"
	printf "\nIf you using this with no argument: \e[1;32mwill show in-this-path '$PWD' projects\e[0m\n"
	return 5
fi

if [[ -z $1 ]];then
	folders=$(ls --all "$PWD")
else
	folders=$(ls --all "$1")
fi

list=""

for folder in ${folders[@]};do
	if [[ -d "$PWD/$folder" ]];then
		in_folders=$(ls --all "$folder")
		for in_folder in ${in_folders[@]};do
			full_in_folder_path="$PWD/$folder/.dbg/prj.info"
			if [[ -f $full_in_folder_path ]];then
				list+="\t$folder\n"
				break
			fi
		done
	fi
done

printf "projects:\n$list"

export list
