#!/bin/bash
if [[ $1 == "--help" ]];then
	printf "\e[7mUse For:\e[0m\n\tmove the content of project to other directory\n"
	printf "\e[7mThe How to Using:\e[0m\n\tskprj <mv> [arguments]\n"
	printf "\t\t   [mv_to_path]\n"
	printf "\e[7mArgs:\e[0m\n"
	printf "\t1)\e[1;32mmv_to_path\e[0m: new project folder name \e[1;30m:create new directory and move the project to it\e[0m\n"
	printf "\nIf you using this with '\$SK_PRJ_NAME' not define: \e[1;32mit will ask you for a prj-name\e[0m\n"
	return 5
fi

if [[ -z $SK_PRJ_NAME ]];then
	printf "project name:"
	read SK_PRJ_NAME
fi

if [[ -z $1 ]];then
	printf "move to: "
	read mv_to_path
else
	mv_to_path=$1
fi

mkdir -p $mv_to_path
mv -r $SK_PRJ_NAME/* $mv_to_path
echo "project '$SK_PRJ_NAME' move contains to '$mv_to_path'"

printf "Do you want to delete the old-prj-folder '$SK_PRJ_NAME' [Y/*]: "
read delete_ansr
if [[ $delete_ansr == "Y" || $delete_ansr == "y" ]];then
	rm -rf "./$SK_PRJ_NAME"
fi
